# file: GNUmakefile
#

# define the source files
#
ISIP_LIB_FILES = *.make *.sh
ISIP_BIN_FILES = 

# define the files these source files depend on (usually include files)
#
ISIP_DEPS = 

# define the extension which will be striped from executables
#
BIN_EXT =

# define the installation directories (appended to $ISIP_IFC/bin/scripts
# and $ISIP_IFC/lib/scripts)
#
ISIP_LIB = make

# tell the scripts.make that we are building make (it does includes a
# little differently to get around the chicken and egg problem).
#
MAKING_MAKE = true

# include the isip standard make template
#
include ./scripts.make

#
# end of file

