# file: GNUmakefile
#

# define the source files
#
ISIP_LIB_FILES = *.pm
ISIP_BIN_FILES = 

# define the files these source files depend on (usually include files)
#
ISIP_DEPS = 

# define the extension which will be striped from executables
#
BIN_EXT = .pl

# define the installation directories (appended to $ISIP/bin/scripts
# and $ISIP/lib/scripts)
#
ISIP_BIN = 
ISIP_LIB = perl

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/scripts.make

#
# end of file

