# file: $isip/class/numeric/Sigmoid/GNUmakefile	
# version: $Id: GNUmakefile 6204 2001-01-19 23:36:13Z hamaker $
#

# source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = Sigmoid.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = 

# compilation flags: optimize and debug
# 
ISIP_CFLAGS = 

# output library
# 
ISIP_OLIB = lib_numeric.a

# make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
