# file: $isip/class/numeric/Bessel/GNUmakefile
# version: $Id: GNUmakefile 7146 2001-07-04 22:57:40Z picone $
#

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = Bessel.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = Float.h MemoryManager.h

# define the output library
#
ISIP_OLIB = lib_numeric.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
