# file: $isip/class/dstr/DstrBase/GNUmakefile
# version: $Id: GNUmakefile 5478 2000-11-09 21:34:29Z duncan $
#
# this make file builds the DstrBase class
#

# define the source files
#
ISIP_FILES =

# define the header files that need to be installed
#
ISIP_HEADER_FILES = DstrBase.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = String.h

# define the compilation flags
# 
ISIP_CFLAGS =

# no diagnostics for this class
#
ISIP_DIAGNOSE_MODE = none

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
