# file: $isip/class/shell/DebugLevel/GNUmakefile
# version: $Id
#
# this make file builds the DebugLevel class
# 

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = DebugLevel.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = Long.h NameMap.h

# define the output library
#
ISIP_OLIB = lib_shell.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
