# file: $isip/class/mmedia/GNUmakefile
# version: $Id: GNUmakefile 10287 2005-11-01 22:06:21Z wholland $
#
# this make file builds the mmedia class hierarchy recursively
#

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/traverse.make

#
# end of file
