# file: $isip/class/shell/CommandLine/GNUmakefile
# version: $Id: GNUmakefile 6228 2001-01-23 22:05:37Z peng $
#
# this make file builds the CommandLine class
#

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = CommandLine.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = Sdb.h Filename.h String.h Boolean.h Vector.h SingleLinkedList.h

# define the output library
#
ISIP_OLIB = lib_shell.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
