# file: $isip/class/shell/Filename/GNUmakefile
#

# source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = Filename.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = String.h

# define the compilation flags
# 
ISIP_CFLAGS = 

# output library
# 
ISIP_OLIB = lib_shell.a

# make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file

