# file: $isip/class/math/vector/VectorComplexFloat/GNUmakefile
# version: $Id: GNUmakefile 7289 2001-08-09 00:28:43Z picone $
#
# this make file builds the VectorComplexFloat class
# 

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = VectorComplexFloat.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = MVector.h

# define the output library
#
ISIP_OLIB = lib_math_vector.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
