# file: $isip/class/numeric/Bark/GNUmakefile
# version: $Id: GNUmakefile 6810 2001-04-24 19:22:15Z srivasta $
#
# this make file builds the Warp class
#

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = Wishart.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = VectorFloat.h  Random.h MemoryManager.h SysString.h

# define the output library
#
ISIP_OLIB = lib_numeric.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
