# file: $isip/class/system/Integral/GNUmakefile
# version: $Id: GNUmakefile 6224 2001-01-23 21:09:30Z duncan $
#
# this make file builds the Integral class
# 

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = Integral.h IntegralTypes.h IntegralConfigure.h \
	IntegralNameSpace.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = SysString.h SysComplex.h

# define the output library
#
ISIP_OLIB = lib_system.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
