# file: $isip/class/algo/Kernel/GNUmakefile
# version: $Id: GNUmakefile 7197 2001-07-20 15:51:56Z hamaker $
#
# this make file builds the Kernel class
#

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = Kernel.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = 

# define the output library
#
ISIP_OLIB = lib_numeric.a

# define the compilation flags
# 
ISIP_CFLAGS = 

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
