# file: $isip/class/math/GNUmakefile
# version: $Id: GNUmakefile 5283 2000-10-10 20:57:29Z duncan $
#
# this make file builds the math class hierarchy recursively
# 

# define the order these three are built
#
ISIP_ORDER = scalar/ vector/ matrix/

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/traverse.make

#
# end of file
