# file: $isip/class/math/scalar/ComplexLong/GNUmakefile
# version: $Id: GNUmakefile 7286 2001-08-07 03:53:12Z picone $
#
# this make file builds the ComplexLong class
# 

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = ComplexLong.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = MComplexScalar.h Long.h

# define the output library
#
ISIP_OLIB = lib_math_scalar.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
