chmod a-x Boolean/Boolean.h
chmod a-x Boolean/bool_00.cc
chmod a-x Boolean/bool_01.cc
chmod a-x Boolean/bool_02.cc
chmod a-x Boolean/bool_03.cc
chmod a-x Boolean/bool_04.cc
chmod a-x Byte/Byte.h
chmod a-x Byte/byte_00.cc
chmod a-x Byte/byte_01.cc
chmod a-x Byte/byte_02.cc
chmod a-x Char/Char.h
chmod a-x Char/char_00.cc
chmod a-x Char/char_01.cc
chmod a-x Char/char_02.cc
chmod a-x Char/char_03.cc
chmod a-x Char/char_04.cc
chmod a-x ComplexDouble/ComplexDouble.h
chmod a-x ComplexDouble/cdbl_00.cc
chmod a-x ComplexDouble/cdbl_01.cc
chmod a-x ComplexDouble/cdbl_02.cc
chmod a-x ComplexFloat/ComplexFloat.h
chmod a-x ComplexFloat/cflt_00.cc
chmod a-x ComplexFloat/cflt_01.cc
chmod a-x ComplexFloat/cflt_02.cc
chmod a-x ComplexLong/ComplexLong.h
chmod a-x ComplexLong/clong_00.cc
chmod a-x ComplexLong/clong_01.cc
chmod a-x ComplexLong/clong_02.cc
chmod a-x Double/Double.h
chmod a-x Double/dbl_00.cc
chmod a-x Double/dbl_01.cc
chmod a-x Double/dbl_02.cc
chmod a-x Float/Float.h
chmod a-x Float/flt_00.cc
chmod a-x Float/flt_01.cc
chmod a-x Float/flt_02.cc
chmod a-x Llong/Llong.h
chmod a-x Llong/llng_00.cc
chmod a-x Llong/llng_01.cc
chmod a-x Llong/llng_02.cc
chmod a-x Long/Long.h
chmod a-x Long/long_00.cc
chmod a-x Long/long_01.cc
chmod a-x Long/long_02.cc
chmod a-x MComplexScalar/MComplexScalar.h
chmod a-x MComplexScalar/MComplexScalarMethods.h
chmod a-x MComplexScalar/mcscl_00.cc
chmod a-x MComplexScalar/mcscl_02.cc
chmod a-x MComplexScalar/mcscl_03.cc
chmod a-x MComplexScalar/mcscl_04.cc
chmod a-x MComplexScalar/mcscl_06.cc
chmod a-x MScalar/MScalar.h
chmod a-x MScalar/MScalarMethods.h
chmod a-x MScalar/mscl_00.cc
chmod a-x MScalar/mscl_02.cc
chmod a-x MScalar/mscl_03.cc
chmod a-x MScalar/mscl_04.cc
chmod a-x MScalar/mscl_05.cc
chmod a-x MScalar/mscl_06.cc
chmod a-x Short/Short.h
chmod a-x Short/shrt_00.cc
chmod a-x Short/shrt_01.cc
chmod a-x Short/shrt_02.cc
chmod a-x String/String.h
chmod a-x String/str_00.cc
chmod a-x String/str_01.cc
chmod a-x String/str_02.cc
chmod a-x String/str_03.cc
chmod a-x String/str_04.cc
chmod a-x String/str_05.cc
chmod a-x Ullong/Ullong.h
chmod a-x Ullong/ullg_00.cc
chmod a-x Ullong/ullg_01.cc
chmod a-x Ullong/ullg_02.cc
chmod a-x Ulong/Ulong.h
chmod a-x Ulong/ulng_00.cc
chmod a-x Ulong/ulng_01.cc
chmod a-x Ulong/ulng_02.cc
chmod a-x Ushort/Ushort.h
chmod a-x Ushort/usht_00.cc
chmod a-x Ushort/usht_01.cc
chmod a-x Ushort/usht_02.cc
