# file: $isip/class/dstr/GNUmakefile
# version: $Id: GNUmakefile 8942 2002-12-26 20:28:50Z alphonso $
#
# this make file builds the dstr class hierarchy recursively
# 

# add an exclude for the graph classes
#
ISIP_EXCLUDE = Tree/ TreeNode/

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/traverse.make

#
# end of file
