# file: $isip/class/shell/NameMap/GNUmakefile
# version: $Id: GNUmakefile 5871 2000-12-13 23:36:00Z duncan $
#
# this make file builds the NameMap class
# 

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = NameMap.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = SysString.h Checksum.h MemoryManager.h

# define the compilation flags
# 
ISIP_CFLAGS =

# define the output library
#
ISIP_OLIB = lib_io.a

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
