# file: $isip/class/system/Console/GNUmakefile
# version: $Id: GNUmakefile 5283 2000-10-10 20:57:29Z duncan $
#
# this make file builds the Console class
# 

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = Console.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = File.h Integral.h

# define the output library
#
ISIP_OLIB = lib_system.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
