# file: $isip/class/io/Sof/GNUmakefile
# version: $Id: GNUmakefile 5283 2000-10-10 20:57:29Z duncan $
#
# this make file builds the Sof class
# 

# define the source files
#
ISIP_FILES = *.cc

# define the header files that need to be installed
#
ISIP_HEADER_FILES = Sof.h

# define other dependencies (headers are included automatically)
#
ISIP_DEPS = File.h SofSymbolTable.h SofList.h

# define the output library
#
ISIP_OLIB = lib_io.a

# define the compilation flags
# 
ISIP_CFLAGS =

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/compile.make

#
# end of file
