# file: $isip/class/math/vector/GNUmakefile
# version: $Id: GNUmakefile 6241 2001-01-26 20:44:49Z duncan $
#
# this make file builds the vector class hierarchy recursively
# 

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/traverse.make

#
# end of file
