# file: $isip/class/numeric/GNUmakefile
# version: $Id: GNUmakefile 8767 2002-10-31 21:41:58Z jelinek $
#
# this make file builds the numeric class hierarchy recursively
# 

# include the isip standard make template
#
include $(ISIP_DEVEL)/lib/scripts/make/traverse.make

#
# end of file
